# Generated by Django 5.0.4 on 2024-05-05 15:47

import django.core.validators
import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.CharField(default=1, max_length=10000, verbose_name='text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.FileField(upload_to=post.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'mp4', 'mkv'])], verbose_name='Picture'),
        ),
    ]
